config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'home#about', as: 'about'
  get '/services', to: 'home#services', as: 'services'
  get '/term_of_services', to: 'home#term_of_services', as: 'term_of_services'
  get '/privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :children
  resources :teachers
  resources :pod_requests
  resources :pods do
    resources :reviews
  end
  namespace :api do
    namespace :v1 do
      resources :pods, only: [:index]
    end
  end
end

app/models/pod_request.rb
class PodRequest < ApplicationRecord
  belongs_to :child
  belongs_to :pod
  scope :pending, -> { where(status: 'pending') }
  scope :canceled, -> { where(status: 'canceled') }
  scope :approved, -> { where(status: 'approved') }
  validate :validate_approved_pod_request, on: :update, if: :status_changed_to_approved?
  validate :validate_create_approved_pod_request, on: :create
  def pending?
    status == 'pending'
  end

  def canceled?
    status == 'canceled'
  end

  def approved?
    status == 'approved'
  end

  def validate_create_approved_pod_request
    existing_pod_request = child.pod_requests.find_by(pod: pod)
    return unless existing_pod_request.present?

    errors.add(:base, 'Child already has an approved pod request for this pod')
  end

  def validate_approved_pod_request
    return unless child.approved_pod_request && child.approved_pod_request != self

    errors.add(:base, 'Child already has an approved pod request')
  end

  def status_changed_to_approved?
    status == 'approved' && status_changed?
  end

  def send_status_update_email
    template = case status
               when 'approved'
                 :approved_notification
               when 'canceled'
                 :canceled_notification
               else
                 return
               end

    PodRequestMailer.with(pod_request: self).send(template).deliver_now
  end
end

app/controllers/pod_requests_controller.rb
class PodRequestsController < InheritedResources::Base
  def create
    @pod_request = PodRequest.new(pod_request_params)
    @pod_request.status = 'pending'
    if @pod_request.save
      PodRequestMailer.user_notification(current_user, @pod_request).deliver_now
      PodRequestMailer.admin_notification(current_user, @pod_request).deliver_now
      
      redirect_to @pod_request.child, notice: 'Pod request was successfully created.'
    else
      redirect_to @pod_request.child, notice: 'Child has aleardy requested for this pod.'
    end
  end

 private

    def pod_request_params
      params.require(:pod_request).permit(:child_id, :pod_id, :status)
    end

end

app/helpers/pod_requests_helper.rb
module PodRequestsHelper
end

app/views/pod_requests/_pod_request.html.erb
<div id="<%= dom_id pod_request %>">
  <p>
    <strong>Child:</strong>
    <%= pod_request.child_id %>
  </p>

  <p>
    <strong>Pod:</strong>
    <%= pod_request.pod_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= pod_request.status %>
  </p>

</div>

app/views/pod_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pod requests</h1>

<div id="pod_requests">
  <% @pod_requests.each do |pod_request| %>
    <%= render pod_request %>
    <p>
      <%= link_to "Show this pod request", pod_request %>
    </p>
  <% end %>
</div>

<%= link_to "New pod request", new_pod_request_path %>

app/views/pod_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pod_request %>

<div>
  <%= link_to "Edit this pod request", edit_pod_request_path(@pod_request) %> |
  <%= link_to "Back to pod requests", pod_requests_path %>

  <%= button_to "Destroy this pod request", @pod_request, method: :delete %>
</div>