config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'home#about', as: 'about'
  get '/services', to: 'home#services', as: 'services'
  get '/term_of_services', to: 'home#term_of_services', as: 'term_of_services'
  get '/privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :children
  resources :teachers
  resources :pod_requests
  resources :pods do
    resources :reviews
  end
  namespace :api do
    namespace :v1 do
      resources :pods, only: [:index]
    end
  end
end

app/models/pod.rb
class Pod < ApplicationRecord
  belongs_to :teacher, optional: true
  has_one_attached :image
  has_many :reviews, dependent: :destroy
  has_many :pod_requests
  has_many :children, through: :pod_requests
  validates :name, :address, :grade, :zip_code, presence: true
  validates :grade, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :zip_code, presence: true, format: { with: /\A\d{5}\z/, message: 'should be in the format: 12345' }
  validates :teacher, presence: true, if: :active?
  validate :teacher_grade_match, on: %i[create update]
  validates :teacher_id, uniqueness: { allow_nil: true }

  def active?
    teacher.present?
  end

  def self.active_pods
    where.not(teacher_id: nil)
  end

  def self.pod_requests
    PodRequest.joins(:pod).where(pods: { id: all })
  end

  def approved_children
    children.where(pod_requests: { status: 'approved' })
  end

  private

  def teacher_grade_match
    return unless teacher.present? && teacher.grade != grade

    errors.add(:base, "Teacher's grade must be equal to the pod's grade")
  end
end

app/controllers/api/v1/pods_controller.rb
module Api
    module V1
      class PodsController < ApplicationController
       def index
          zip_code = params[:zip_code]
          pods = Pod.where(zip_code: zip_code).where.not(teacher_id: nil)
          
          render json: pods
        end
      end
    end
  end
  

app/controllers/pods_controller.rb
class PodsController < ApplicationController
  load_and_authorize_resource

  def index
    @pods = Pod.where.not(teacher_id: nil)

    return unless params[:search].present?

    search_term = params[:search]
    if search_term =~ /^grade\s+(\d+)$/i
      grade = Regexp.last_match(1).to_i
      @pods = if grade.between?(1, 5)
                @pods.where(grade: grade)
              else
                @pods.none
              end
    elsif search_term.length == 1 && search_term.to_i.between?(1, 5)
      @pods = @pods.where(grade: search_term)
    else
      @pods = @pods.where('name LIKE ? OR address LIKE ? OR zip_code LIKE ?', "%#{search_term}%", "%#{search_term}%",
                          "%#{search_term}%")
    end

    @search_active = params[:search].present?
  end

  def show
    @pod = Pod.find(params[:id])
    @review = @pod.reviews.build
    @pod_request = PodRequest.new
    @approved_children = @pod.children.joins(:pod_requests).where(pod_requests: { status: 'approved' }).distinct
  end
end

app/helpers/pods_helper.rb
module PodsHelper
end

app/views/pods/_apply_pod.html.erb
<% if current_user %>
  <%= form_with(model: @pod_request, url: pod_requests_path, method: :post) do |form| %>
    <%= form.hidden_field :pod_id, value: @pod.id %>
    <%= form.label :child_id, 'Select Child' %>
    <% assigned_child_ids = @pod.children.pluck(:id) %>
    <% same_grade_children = current_user.children.where(grade: @pod.grade).where.not(id: assigned_child_ids) %>
    <%= form.collection_select(:child_id, same_grade_children, :id, :name, prompt: 'Select a Child', options: options_for_select(same_grade_children.map { |child| [child.name, child.id, { disabled: false }] })) %>
    <%= form.submit 'Apply for Pod' %>
  <% end %>
<% end %>
<br>

app/views/pods/_carousel.html.erb
<div class="container-fluid mt-0" style="background-color: #dededc;">
    <div class="row">
      <div class="col-lg-12"><br>
        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% @pods.each_with_index do |pod, index| %>
              <div class="carousel-item <%= 'active' if index.zero? %>">
               <div class="carousel-caption-new d-none d-md-block">
                    <h5 class="extra-red">Pod Name : <%= pod.name %></h5>
                    <h3 class="extra-red bold ">Grade : <%= pod.grade %></h3>
                  </div>
                  <% if pod.image_url.present?%>
                <%= link_to pod_path(pod) do %>
                    <%= image_tag pod.image_url, class: 'd-block w-100', alt: 'Pod Image' %>
                    <%end%>
                  <% else %>
                <%= link_to pod_path(pod) do %>
                    <%= image_tag 'default_pod.avif', class: 'd-block w-100', alt: 'Default Image' %>
                  <% end %>
                 
                <% end %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
  </div>

app/views/pods/_children_count.html.erb
<% if @approved_children.any? && @approved_children.count >=15  %>
   
  <h1> Pod is full</h1>
  <% elsif %>
  <h4>Children in this Pod: <%= @approved_children.count %></h4>
  <p>REMAINING children: <%= 15-@approved_children.count %></p>
  <% else %>
  <p>No children found for this pod.</p>
<% end %>

app/views/pods/_pod.html.erb
<!-- app/views/your_controller/show.html.erb -->
<div class="row">
  <div class="col-lg-6">
    <div id="<%= dom_id pod %>">
      <p>
        <strong>Name:</strong>
        <%= pod.name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= pod.address %>
      </p>

      <p>
        <strong>Grade:</strong>
        <%= pod.grade %>
      </p>

      <p>
        <strong>ZipCode:</strong>
        <%= pod.zip_code %>
      </p>

      <% if pod.teacher.present? %>
        <p>
          <strong>Assigned Teacher:</strong>
          <% if user_signed_in? %>
            <%= link_to pod.teacher.name, teacher_path(pod.teacher) %>
          <% else %>
            <%= pod.teacher.name %>
          <% end %>
        </p>
      <% end %>
    </div>
  </div>
  <div class="col-lg-4 d-flex justify-content-center align-items-center">
    <!-- Add the image here -->
    <%= image_tag pod.image_url, class: 'img-fluid', alt: 'Pod Image' if pod.image_url.present? %>
  </div>
</div>

app/views/pods/_search.html.erb
<div style="width: 100%;">
  <%= form_tag(pods_path, method: :get, class: "search-form") do %>
    <div style="display: flex; width: 100%;">
      <%= text_field_tag(:search, params[:search], placeholder: "Search by name, address, zip_code, or grade '1 to 5'", style: "width: 100%;") %>
      <%= submit_tag("Search", class: "btn btn-dark", style: "margin-left: 50px;") %>
    </div>
  <% end %>
</div>

app/views/pods/index.html.erb
<section class="margin-header" style="background-color: #f2f2f2">
    <%= render "search" %><br>
      <% unless @search_active %>
       <%= render "carousel" %>
       <%else%>
      <% @pods.each do |pod| %>
      <div class= "container-fluid">
        <h3><%= link_to pod.name, pod_path(pod),style: "text-decoration: none;" %></h3>
        <h4>Grade: <%= pod.grade %></h4>
      </div>
    <% end %>
      <% end %>
</section>

app/views/pods/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="margin-header" style="background-color: #f2f2f2">
<%= link_to "All pods", pods_path %><br><br>
<div>
<%= render @pod %>
<%= render "children_count"%>
<% if user_signed_in?%>
<%= render "apply_pod"%>
  <%else%>
 <h3>please sign in  to apply for this pod</h3>  
</div>
<%end%> 
<%= render "reviews/review" %>
  <% if user_signed_in? && current_user.children.exists?(id: @pod.approved_children.pluck(:id)) %>
  <%= render "reviews/review_form" %>
<%end%>
</div>