config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'home#about', as: 'about'
  get '/services', to: 'home#services', as: 'services'
  get '/term_of_services', to: 'home#term_of_services', as: 'term_of_services'
  get '/privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :children
  resources :teachers
  resources :pod_requests
  resources :pods do
    resources :reviews
  end
  namespace :api do
    namespace :v1 do
      resources :pods, only: [:index]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user
    can :read, :all
      # Define other abilities for non-admin users

  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :user
  has_many :pod_requests
  has_one :approved_pod_request, -> { where(status: 'approved') }, class_name: 'PodRequest'
  has_one :pod, through: :approved_pod_request, source: :pod
  validates :name, :age, :grade, presence: true
  validate :validate_approved_pod_request_count, on: :create
  def validate_approved_pod_request_count
    return unless pod_requests.approved.exists?

    errors.add(:base, 'Child already has an approved pod request')
  end
end

app/models/pod.rb
class Pod < ApplicationRecord
  belongs_to :teacher, optional: true
  has_one_attached :image
  has_many :reviews, dependent: :destroy
  has_many :pod_requests
  has_many :children, through: :pod_requests
  validates :name, :address, :grade, :zip_code, presence: true
  validates :grade, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :zip_code, presence: true, format: { with: /\A\d{5}\z/, message: 'should be in the format: 12345' }
  validates :teacher, presence: true, if: :active?
  validate :teacher_grade_match, on: %i[create update]
  validates :teacher_id, uniqueness: { allow_nil: true }

  def active?
    teacher.present?
  end

  def self.active_pods
    where.not(teacher_id: nil)
  end

  def self.pod_requests
    PodRequest.joins(:pod).where(pods: { id: all })
  end

  def approved_children
    children.where(pod_requests: { status: 'approved' })
  end

  private

  def teacher_grade_match
    return unless teacher.present? && teacher.grade != grade

    errors.add(:base, "Teacher's grade must be equal to the pod's grade")
  end
end

app/models/pod_request.rb
class PodRequest < ApplicationRecord
  belongs_to :child
  belongs_to :pod
  scope :pending, -> { where(status: 'pending') }
  scope :canceled, -> { where(status: 'canceled') }
  scope :approved, -> { where(status: 'approved') }
  validate :validate_approved_pod_request, on: :update, if: :status_changed_to_approved?
  validate :validate_create_approved_pod_request, on: :create
  def pending?
    status == 'pending'
  end

  def canceled?
    status == 'canceled'
  end

  def approved?
    status == 'approved'
  end

  def validate_create_approved_pod_request
    existing_pod_request = child.pod_requests.find_by(pod: pod)
    return unless existing_pod_request.present?

    errors.add(:base, 'Child already has an approved pod request for this pod')
  end

  def validate_approved_pod_request
    return unless child.approved_pod_request && child.approved_pod_request != self

    errors.add(:base, 'Child already has an approved pod request')
  end

  def status_changed_to_approved?
    status == 'approved' && status_changed?
  end

  def send_status_update_email
    template = case status
               when 'approved'
                 :approved_notification
               when 'canceled'
                 :canceled_notification
               else
                 return
               end

    PodRequestMailer.with(pod_request: self).send(template).deliver_now
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :pod
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_one :pod
  validates :grade, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validate :grade_match_with_pod

  def grade_match_with_pod
    return unless pod && grade != pod.grade

    errors.add(:grade, 'must match the grade of the associated pod')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :children, dependent: :destroy
  validates :name, :address, presence: true
  validates :phone_number, presence: true, numericality: { only_integer: true }
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pods = Pod.where.not(teacher_id: nil)

    return unless params[:search].present?

    search_term = params[:search]
    @pods = if search_term.length == 1 && search_term.to_i.between?(1, 5)
              @pods.where(grade: search_term)
            else
              @pods.where('name LIKE ? OR address LIKE ? OR zip_code LIKE ?',
                          "%#{search_term}%", "%#{search_term}%", "%#{search_term}%")
            end
  end

  def about; end
end

app/controllers/pods_controller.rb
class PodsController < ApplicationController
  load_and_authorize_resource

  def index
    @pods = Pod.where.not(teacher_id: nil)

    return unless params[:search].present?

    search_term = params[:search]
    if search_term =~ /^grade\s+(\d+)$/i
      grade = Regexp.last_match(1).to_i
      @pods = if grade.between?(1, 5)
                @pods.where(grade: grade)
              else
                @pods.none
              end
    elsif search_term.length == 1 && search_term.to_i.between?(1, 5)
      @pods = @pods.where(grade: search_term)
    else
      @pods = @pods.where('name LIKE ? OR address LIKE ? OR zip_code LIKE ?', "%#{search_term}%", "%#{search_term}%",
                          "%#{search_term}%")
    end

    @search_active = params[:search].present?
  end

  def show
    @pod = Pod.find(params[:id])
    @review = @pod.reviews.build
    @pod_request = PodRequest.new
    @approved_children = @pod.children.joins(:pod_requests).where(pod_requests: { status: 'approved' }).distinct
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pod_requests_helper.rb
module PodRequestsHelper
end

app/helpers/pods_helper.rb
module PodsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/_header_new.html.erb
<header class="header fixed-top d-flex align-items-center">

   <div class="container-fluid d-flex align-items-center">
      <%= link_to(root_path, class: "logo d-flex align-items-center me-auto me-xl-0") do %>
        <h1>Get School House</h1>
        <span>.</span>
      <% end %>
      <nav class="navmenu">
          <ul class="d-flex justify-content-end mr-8">
           <li><%= link_to"About", about_path%></li>

            <li><%= link_to "Pods", pods_path%>
            </li>
             <% if user_signed_in? %>
            <li><%= link_to "Teachers", teachers_path %>
            </li>
            <li>  <%= link_to " Mychildren", children_path%>
            </li>
            <li> <%= link_to "Add children", new_child_path %>
            </li>
            <li><%= link_to current_user.email , edit_user_registration_path , class: "nav-link " %>
            </li>
            <%else%>
            <li><%= link_to "Sign in" , new_user_session_path %>
            </li>
             <li><%= link_to "Sign up", new_user_registration_path%>
            </li>
            <%end%>
          </ul>


          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>
        <% if user_signed_in? %>
          <%= link_to "Sign out" , destroy_user_session_path , data: { "turbo-method": :delete } ,  class: "btn-getstarted ms-auto" %>
          <%end%>
      </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetSchoolHouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
      rel="stylesheet"
    />

   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"> 

   <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css" rel="stylesheet"> 
  <%=  stylesheet_link_tag "application", "data-turbo-track": "reload" %>  
</head>

 <body>
   <%= render "layouts/header_new"%>
   <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'new_test' %>
    <%= javascript_include_tag 'main' %>
</body>
</html>